apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hello-express
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
