apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: hello-express
  labels:
    app: postgres
    replicationRole: replica
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: postgres
    replicationRole: replica