apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: hello-express
  labels:
    app: postgres
    replicationRole: primary
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: postgres
    replicationRole: primary