kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hello-express-data-pv-claim
  labels:
    app: hello-express
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi