apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-express
  namespace: hello-express
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: hello-express
  template:
    metadata:
      labels:
        run: hello-express
    spec:
      containers:
      - name: hello-express
        image: bayar/hello-express:main
        ports:
        - name: http
          containerPort: 8080
