apiVersion: v1
kind: Service
metadata:
  name: hello-express-svc
  namespace: hello-express
  labels:
    run: hello-express
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: hello-express
