kind: PersistentVolume
apiVersion: v1
metadata:
  name: hello-express-pv-volume
  labels:
    type: local
    app: hello-express
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/persistent-volumes/hello-express"